// generated by zed-pkg-test/test-org-fleet; edit the fleet manifest or bootstrapper, not this file.
import fs from 'node:fs';
import childProcess from 'node:child_process';

const plan = JSON.parse(fs.readFileSync(new URL('../test-plan.json', import.meta.url), 'utf8'));
const errors = [];
if (plan.schemaVersion !== 1) errors.push('schemaVersion must be 1');
if (!plan.repository || !plan.profile) errors.push('repository and profile are required');
if (!Array.isArray(plan.focus) || plan.focus.length < 2) errors.push('focus must contain at least two assertions');
if (!Array.isArray(plan.sources) || plan.sources.length === 0) errors.push('at least one source is required');
for (const source of plan.sources ?? []) {
  if (source.exists && !/^[0-9a-f]{40}$/.test(source.sha ?? '')) errors.push('existing source must be pinned to a 40-character SHA: ' + source.fullName);
}
for (const dependency of plan.imports ?? []) {
  if (!['git-submodule', 'zed', 'native-package'].includes(dependency.mode)) errors.push('unsupported dependency mode: ' + dependency.mode);
}
if (fs.existsSync(new URL('../.gitmodules', import.meta.url))) {
  const tree = childProcess.execFileSync('git', ['ls-tree', 'HEAD'], { encoding: 'utf8' });
  for (const dependency of plan.imports.filter((item) => item.mode === 'git-submodule')) {
    if (!tree.includes('160000 commit') || !tree.includes(dependency.path)) errors.push('missing gitlink for ' + dependency.path);
  }
}
const serialized = JSON.stringify(plan);
if (/ghp_[A-Za-z0-9]+|github_pat_[A-Za-z0-9_]+/.test(serialized)) errors.push('credential-shaped value found');
if (errors.length) { for (const error of errors) console.error('error: ' + error); process.exit(1); }
console.log('validated generated test plan for ' + plan.testOrganization + '/' + plan.repository);
